apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.Version}}
spec:
  selector:
    layer: dbildungs-iam-keycloak
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: web
  type: ClusterIP
  