apiVersion: v1
kind: Secret
metadata:
  name: realm-config-secret
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.Version}}
type: opaque
data:
  realm-spsh.json: |-
      {{.Files.Get "dev-realm-spsh-225.json" | b64enc}}
