@host = 127.0.0.1
@port = 9090

###

GET http://{{host}}:{{port}}/docs HTTP/1.1

###

POST http://{{host}}:{{port}}/api/organisation HTTP/1.1
Content-Type: application/json

{
    "kennung": "NI-HK-KGS",
    "name": "Kooperative Gesamtschule Schwarmstedt",
    "namensergaenzung": "string",
    "kuerzel": "KGS",
    "typ": "SCHULE"
}

###

@orgId = 78d9ae41-a101-4947-82cc-b0545d2b2e85

GET http://{{host}}:{{port}}/api/organisation/{{orgId}} HTTP/1.1

###

GET http://localhost:8080/metrics HTTP/1.1
