apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: dbildungs-iam
spec:
  selector:
    layer: dbildungs-iam-keycloak
  ports:
    - protocol: TCP
      name: web
      port: {{.Values.dbildungsIamExternalPort}}80
      targetPort: web
  type: ClusterIP
  