{{- if not (lookup "v1" "Secret" .Release.Namespace .Values.secrets.name ) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbiam-deployment-backend
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.Version}}
spec:
  selector:
    matchLabels:
      layer: dbildungs-iam-backend
  replicas: {{.Values.dbildungsIamReplications}}
  template:
    metadata:
      name: dbildungs-iam
      labels:
        layer: dbildungs-iam-backend
    spec:
      containers:
        - name: dbildungs-iam-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: web
              containerPort: 8080
          env:
          {{- include "dbiam-backend-envs" . | indent  12}}
          volumeMounts:
            - mountPath: /app/config/
              name: config-volume
              readOnly: true
            - mountPath: /app/secrets/
              name: secret-volume
              readOnly: true
          resources:
            requests:
              cpu: {{.Values.dbildungsIamCpuRequest}}
              memory: {{.Values.dbildungsIamMemRequest}}
            limits:
              cpu: {{.Values.dbildungsIamCpuMax}}
              memory: {{.Values.dbildungsIamMemMax}}
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              port: 8080
              scheme: 'HTTP'
              path: '/health'
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              port: 8080
              scheme: 'HTTP'
              path: '/health'
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: {{.Values.configmap.name  }}
        - name: secret-volume
          secret:
            secretName: {{.Values.secrets.name}}
