apiVersion: v1
kind: Service
metadata:
  name: dbiam-service
  labels:
    app.kubernetes.io/name: dbildungs-iam
spec:
  selector:
    name: dbildungs-iam
  ports:
    - protocol: TCP
      name: web
      port: {{.Values.dbildungsIamExternalPort}}
      targetPort: web
  type: ClusterIP
  