apiVersion: v1
kind: Service
metadata:
  name: dbiam-bff
  labels:
    app.kubernetes.io/name: dbildungs-iam
spec:
  selector:
    layer: dbildungs-iam-bff
  ports:
    - protocol: TCP
      name: web
      port: {{.Values.dbildungsIamExternalPort}}
      targetPort: web
  type: ClusterIP