apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name }}-services
spec:
  selector:
    app: dbildungs-iam
  ports:
    - protocol: TCP
      port: {{.Values.dbildungsIamExternalPort}}
      targetPort: 8080
  type: ClusterIP
  