{{if not (lookup "v1" "ConfigMap" .Release.Namespace .Values.configmap.name)}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  config.json: |-
    {{ .Files.Get "config/config.json" | nindent 4 }}
  keycloak-base-url: "http://keycloak:80"
  frontend-oidc-callback-url: "https://{{.Values.backendHostname}}/api/frontend/login"
  frontend-default-login-redirect: "https://{{.Values.backendHostname}}/"
  frontend-logout-redirect: "https://{{.Values.backendHostname}}/"

{{end}}
