apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.releasename" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.backend.commonLabels.name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/layer: {{ .Values.backend.selector.layer }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.backend.commonLabels.name }}
        app.kubernetes.io/layer: {{ .Values.backend.selector.layer }}
    spec:
      {{- if .Values.seeding.enabled }}
      initContainers:
        {{- range .Values.initContainers }}
        - name: {{ .name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          securityContext:
            allowPrivilegeEscalation: false
          command: {{ .command }}
          env:
            {{- include "dbiam-backend-envs" $ | nindent 12 }}
          volumeMounts:
            {{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath | default "" }}
              readOnly: {{ .readOnly }}
            {{- end }}
          resources: 
            {{- toYaml $.Values.containerResources | nindent 12 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Values.backend.commonLabels.name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.enabledcontainerSecurityContext }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ (index .Values.backendcontainer.ports 0).name }}
              containerPort: {{ (index .Values.backendcontainer.ports 0).containerPort }}
          env:
            {{- include "dbiam-backend-envs" . | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.backendcontainer.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.containerResources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.backendcontainer.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backendcontainer.readinessProbe | nindent 12 }}
      restartPolicy: {{.Values.restartPolicy  }}
      volumes:
        - name: {{ .Values.backendcontainer.volumeMounts.configVolume.name }}
          configMap:
            name:  {{.Values.configmap.name  }}
        - name: {{ .Values.backendcontainer.volumeMounts.secretVolume.name }}
          secret:
            secretName: {{.Values.secrets.name}}
        {{if .Values.seeding}}
        - name: seeding-volume
          configMap:
            name: {{.Values.seeding.configmap}}
        {{end}}
