apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbiam-deployment-backend
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.Version}}
spec:
  selector:
    matchLabels:
      layer: dbildungs-iam-backend
  replicas: {{.Values.dbildungsIamReplications}}
  template:
    metadata:
      name: dbildungs-iam
      labels:
        layer: dbildungs-iam-backend
    spec:
      initContainers:
        - name: db-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          securityContext:
            allowPrivilegeEscalation: false
          command: [ "node", "dist/src/console/main.js", "db", "init" ]
          env:
            - name: NODE_ENV
              value: {{.Values.environment}}
            - name: DEPLOY_STAGE
              value: {{.Values.environment}}
          volumeMounts:
            - mountPath: /app/config/
              name: config
              readOnly: true
            - mountPath: /app/sql/{{.Values.environment}}
              name: seeding
              readOnly: true
        - name: db-seeding
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          securityContext:
            allowPrivilegeEscalation: false
          command: [ "node", "dist/src/console/main.js", "db", "seed", "prod", "" ]
          env:
            - name: NODE_ENV
              value: {{.Values.environment}}
            - name: DEPLOY_STAGE
              value: {{.Values.environment}}
          volumeMounts:
            - mountPath: /app/config/
              name: config
              readOnly: true
            - mountPath: /app/sql/{{.Values.environment}}
              name: seeding
              readOnly: true
      containers:
        - name: dbildungs-iam-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          ports:
             - name: web
               containerPort: 8080
          env:
            - name: NODE_ENV
              value: {{.Values.environment}}
            - name: DEPLOY_STAGE
              value: {{.Values.environment}}
          volumeMounts:
            - mountPath: /app/config/
              name: config-volume
              readOnly: true
            - mountPath: /app/secrets/
              name: secret-volume
              readOnly: true
          resources:
            requests:
              cpu: {{.Values.dbildungsIamCpuRequest}}
              memory: {{.Values.dbildungsIamMemRequest}}
            limits:
              cpu: {{.Values.dbildungsIamCpuMax}}
              memory: {{.Values.dbildungsIamMemMax}}
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              port: 8080
              scheme: 'HTTP'
              path: '/health'
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              port: 8080
              scheme: 'HTTP'
              path: '/health'
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: dbildungs-iam-configmap
        - name: secret-volume
          secret:
            secretName: dbildungs-iam-secrets
        - name: seeding
          secret:
            secretName: {{.Values.seedingData | default (print .Release.Name "-secret")}}
