apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-secret
  labels:
    app.kubernetes.io/name: dbildungs-iam
data:
  config.dev.json: |-
{{.Files.Get .Values.configfile.dev | b64enc | indent 4}}
  config.test.json: |-
{{.Files.Get .Values.configfile.test | b64enc | indent 4}}
  config.prod.json: |-
{{.Files.Get .Values.configfile.prod | b64enc | indent 4}}
  secrets.json: |-
{{.Files.Get .Values.configfile.secrets | b64enc | indent 4}}