apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.releasename" . }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.dbiam.commonLabels.name }}
    app.kubernetes.io/version: {{.Chart.Version}}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/layer: {{ .Values.dbiam.selector.layer }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.dbiam.commonLabels.name }}
        app.kubernetes.io/layer: {{ .Values.dbiam.selector.layer }} 
    spec:
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      securityContext:
        allowPrivilegeEscalation: false
      initContainers:
        {{- range .Values.redisinitContainer }}
        - name: {{ .name }}
          image: {{ .image }}
          command: {{ .command }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          securityContext:
            {{- toYaml $.Values.containerSecurityContext | nindent 12 }}
        {{- end }}
      containers:
        - name: {{ .Values.redis.image.name }}
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            {{- toYaml .Values.redisports | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.redis.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.containerResources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.redis.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.redis.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.redis.startupProbe | nindent 12 }}
      volumes:
        {{- toYaml .Values.redisvolumes | nindent 8 }}
      restartPolicy: {{ .Values.restartPolicy }}