apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.Version}}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis-port
      protocol: TCP
      name: redis-port
  selector:
    layer: dbildungs-iam-redis
