apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.releasename" . }}-redis
  namespace: {{ .Values.namespace }}
  labels: 
    app.kubernetes.io/name: {{ .Values.dbiam.commonLabels.name }}
    app.kubernetes.io/version: {{.Chart.Version}}
spec:
  selector:
    app.kubernetes.io/layer: {{ .Values.dbiam.selector.layer }}
  type: {{ .Values.redisservicetype }}
  {{- if .Values.enabledredisserviceport }}
  ports: {{- toYaml .Values.redisports | nindent 6 }}
  {{- end }}
