apiVersion: v1
kind: ConfigMap
metadata:
  name: dbiam-redis-tls-config
data:
{{(.Files.Glob "gencert.sh").AsConfig | indent 2}}
{{(.Files.Glob "copy-tls.sh").AsConfig | indent 2}}
{{(.Files.Glob "redis.conf").AsConfig | indent 2}}