apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dbildungs-iam.redisDeploymentName" . }}
  labels:
    {{- include "dbildungs-iam.redisLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dbildungs-iam.redisLayerLabel" . | nindent 6 }}
  replicas: {{ .Values.redisReplications }}
  template:
    metadata:
      name: {{ include "dbildungs-iam.redisMetadataName" . }}
      labels:
        {{- include "dbildungs-iam.redisLayerLabel" . | nindent 8 }}
    spec:
      initContainers:
        - name: copy-tls-data
          image: alpine
          securityContext:
            allowPrivilegeEscalation: false
          command: ["/bin/sh", "-c", "apk add --no-cache openssl bash;/bin/bash /tls/copy-tls.sh"]
          volumeMounts:
            - mountPath: "/tls"
              name: tls-data
            - mountPath: "/data"
              name: data
      containers:
        - name: {{ include "dbildungs-iam.redisContainerName" . }}
          image: redis:7.2.2
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: "/data"
              name: data
          ports:
            - name: {{ include "dbildungs-iam.redisPortName" . }}
              containerPort: 6379
              protocol: TCP
          args:
            - "/data/tls/redis.conf"
      volumes:
        - name: tls-data
          configMap:
            name: {{ include "dbildungs-iam.redisConfigMapName" . }}
        - name: data
          emptyDir: {}
