apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbiam-server-redis-deployment
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.Version}}
spec:
  selector:
    matchLabels:
      layer: dbildungs-iam-redis
  replicas: 1
  template:
    metadata:
      name: dbildungs-iam-redis
      labels:
        layer: dbildungs-iam-redis
    spec:
      initContainers:
        - name: copy-tls-data
          image: alpine
          securityContext:
            allowPrivilegeEscalation: false
          command: ["/bin/sh","-c", "apk add --no-cache openssl bash;/bin/bash /tls/copy-tls.sh"]
          volumeMounts:
            - mountPath: "/tls"
              name: tls-data
            - mountPath: "/data"
              name: data
          resources:
            requests:
              cpu: {{.Values.dbildungsIamRedisCpuRequest}}
              memory: {{.Values.dbildungsIamRedisMemRequest}}
            limits:
              cpu: {{.Values.dbildungsIamRedisCpuMax}}
              memory: {{.Values.dbildungsIamRedisMemMax}}
      containers:
        - name: redis
          image: redis:7.2.2
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: "/data"
              name: data
          ports:
            - name: redis-port
              containerPort: 6379
              protocol: TCP
          args:
            - "/data/tls/redis.conf"
      volumes:
        - name: tls-data
          configMap:
            name: dbiam-redis-tls-config
        - name: data
          emptyDir: {}