apiVersion: v1
kind: ConfigMap
metadata:
  name: dbiam-redis-tls-config
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.Version}}
data:
{{(.Files.Glob "gencert.sh").AsConfig | indent 2}}
{{(.Files.Glob "copy-tls.sh").AsConfig | indent 2}}
{{(.Files.Glob "redis.conf").AsConfig | indent 2}}