apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.releasename" . }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.dbiam.commonLabels.name }}
    app.kubernetes.io/version: {{.Chart.Version}}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/layer: {{ .Values.dbiam.selector.layer }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.dbiam.commonLabels.name }}
        app.kubernetes.io/layer: {{ .Values.dbiam.selector.layer }} 
    spec:
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- if .Values.enabledredisinitContainer }}
      initContainers: {{- toYaml .Values.redisinitContainer | nindent 6 }}
      {{- end }}
      
      {{- if .Values.enabledrediscontainer }}
      containers: {{- toYaml .Values.rediscontainers | nindent 6 }}
      {{- end }}

      {{- if .Values.enabledredisvolume }}
      volumes: {{- toYaml .Values.redisvolumes | nindent 6 }}
      {{- end }}



      