apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.releasename" . }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.dbiam.commonLabels.name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/layer: {{ .Values.redis.selector.layer }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.redis.commonLabels.name }}
        app.kubernetes.io/layer: {{ .Values.redis.selector.layer }}
    spec:
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      initContainers:
        {{- range .Values.redisinitContainer }}
        - name: {{ .name }}
          image: {{ .image }}
          command: ["/bin/sh", "-c", "apk add --no-cache openssl bash;/bin/bash /tls/copy-tls.sh"]
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          command: ["/bin/sh","-c", "apk add --no-cache openssl bash;/bin/bash /tls/copy-tls.sh"]
          volumeMounts:
            - mountPath: "/tls"
              name: tls-data
            - mountPath: "/data"
              name: data
          resources:
            requests:
              cpu: {{.Values.dbildungsIamRedisCpuRequest}}
              memory: {{.Values.dbildungsIamRedisMemRequest}}
            limits:
              cpu: {{.Values.dbildungsIamRedisCpuMax}}
              memory: {{.Values.dbildungsIamRedisMemMax}}
      containers:
        - name: {{ .Values.rediscontainer.image.name }}
          image: {{ .Values.rediscontainer.image.repository }}:{{ .Values.rediscontainer.image.tag }}
          imagePullPolicy: {{ .Values.rediscontainer.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            {{- toYaml .Values.rediscontainer.ports | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.rediscontainer.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.containerResources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.rediscontainer.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.rediscontainer.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.rediscontainer.startupProbe | nindent 12 }}
      volumes:
        {{- toYaml .Values.redisvolumes | nindent 8 }}
      restartPolicy: {{ .Values.restartPolicy }}
