apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: dbildungs-iam
spec:
  selector:
    matchLabels:
      layer: dbildungs-iam-redis
  replicas: 1
  template:
    metadata:
      name: dbildungs-iam-redis
      labels:
        layer: dbildungs-iam-redis
    spec:
      initContainers:
        - name: copy-tls-data
          image: alpine
          command: ["/bin/sh","-c", "apk add --no-cache openssl bash;/bin/bash /tls/copy-tls.sh"]
          volumeMounts:
            - mountPath: "/tls"
              name: tls-data
            - mountPath: "/data"
              name: data
      containers:
        - name: redis
          image: redis:7.2.2
          volumeMounts:
            - mountPath: "/data"
              name: data
          ports:
            - name: redis-port
              containerPort: 6379
              hostPort: 6379
          args:
            - "/data/tls/redis.conf"
      volumes:
        - name: tls-data
          configMap:
            name: dbiam-redis-tls-config
        - name: data
          emptyDir: {}