{{if .Values.backend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "common.names.name" . }}-backend
  namespace: {{ template "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.backend.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.backendHostname }}
      http:
        paths:
          {{- range $path := .Values.backend.ingress.paths }}
          - path: {{ $path }}
            pathType: {{ $.Values.backend.ingress.pathType }}
            backend:
              service:
                name: {{ template "common.names.name" $ }}-backend
                port:
                  number: {{ $.Values.backend.service.ports.http }}
          {{- end }}
{{ end }}