{{if and (.Values.backend.dbseeding.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.name" . }}-backend-seeding
  namespace: {{ template "common.names.namespace" . }}
  labels: 
    {{- include "common.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "seeding/dev/*").AsConfig | indent 2 }}
{{end}}
