apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.name" . }}-backend-migration
  namespace: {{ template "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "migrations/*").AsConfig | indent 2 }}
