{{- range $job_name, $job_options := .Values.cronjobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "common.names.namespace" . }}-trigger-xyz
  namespace: {{ template "common.names.namespace" $ }}
spec:
  schedule: {{ $job_options.schedule }}
  startingDeadlineSeconds: 300
  suspend: true
  jobTemplate:
    spec:
      completions: {{ $job_options.jobsParallelism }} #why is this even working?
      parallelism: {{ $job_options.jobsParallelism }}
      backoffLimit: 0
      template:
        metadata:
          labels:
            test: dbildings-iam-server-{{ $job_options.serviceName }}
            pod: {{ $job_name }}
        spec:
          automountServiceAccountToken: false
          containers:
          - name: {{ $job_name }}
            image: alpine:{{ $job_options.imageTag }}
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
            envFrom:
              - configMapRef:
                  name:  cronjob-envs-configmap
            command:
              - "sh"
              - "-c"
              - |
                  apk update && 
                  apk add --no-cache bash openssl curl cronie jq vim &&
                  chmod +x /scripts/*.sh &&
                  chmod 600 /etc/crontabs/root &&
                  touch /var/log/cron.log && 
                  chmod 644 /var/log/cron.log &&
                  ./scripts/trigger_xyz.sh
            volumeMounts:
              - name: secret-volume
                mountPath: /secrets
                readOnly: true
              - name: secret-volume-jwks
                mountPath: /keys
                readOnly: true
              - name: script-volume
                mountPath: /scripts
            ports:
            - containerPort: {{ $job_options.port }}
              name: dbildings-iam-server-trigger-xyz-pod  
          volumes:
          - name: script-volume
            configMap:
              name: cronjob-scripts-configmap
          - name: secret-volume-jwks
            secret:
              secretName: cronjob-secret-service-acc-jwks
          restartPolicy: Never
---
{{- end}}