{{- range $job_name, $job_options := .Values.cronjobs.jobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dbp-1022-cronjob-dev-{{ $job_name}}
  #name: {{ template "common.names.namespace" $ }}-{{ $job_name}}
  namespace: {{ template "common.names.namespace" $ }}
spec:
  schedule: {{ $.Values.cronjobs.schedule }}
  startingDeadlineSeconds: 300
  suspend: true
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            test: dbildungs-iam-server-{{ $job_name }}
            pod: {{ $job_name }}
        spec:
          automountServiceAccountToken: false
          containers:
          - name: {{ $job_name }}
            image: alpine:{{ $.Values.cronjobs.imageTag }}
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
            envFrom:
              - configMapRef:
                  name:  cronjob-envs-configmap
            command:
              - "sh"
              - "-c"
              - |
                  apk update && 
                  apk add --no-cache bash openssl curl cronie jq vim &&
                  mkdir /scripts &&
                  cp /scripts_tmp/*.sh /scripts/ &&
                  chmod +x /scripts/*.sh &&
                  chmod 600 /etc/crontabs/root &&
                  touch /var/log/cron.log && 
                  chmod 644 /var/log/cron.log &&
                  export BACKEND_HOSTNAME="{{ $.Values.backendHostname}}{{ $job_options.endpoint}}" &&
                  cd {{ $.Values.cronjobs.scriptDir}} &&
                  ./{{ $job_options.script}}
            volumeMounts:
              - name: secret-volume-jwks
                mountPath: /keys
                readOnly: true
              - name: script-volume
                mountPath: /scripts_tmp
                readOnly: false
            ports:
            - containerPort: {{ $.Values.cronjobs.port }}
              name: trigger-xyz-pod  
          volumes:
          - name: script-volume
            configMap:
              name: cronjob-scripts-configmap
          - name: secret-volume-jwks
            secret:
              secretName: cronjob-secret-service-acc-jwks
              items:
              - key: service-account-private-jwks
                path: jwks.json
          restartPolicy: Never
---
{{- end}}