{{- range $job_name, $job_options := .Values.cronjobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dbildings-iam-server-{{ $job_name }}
  namespace: spsh-{{ $.Values.schedule }}
spec:
  schedule: {{ $.Values.schedule }}
  startingDeadlineSeconds: 300
  suspend: true
  jobTemplate:
    spec:
      completions: {{ $job_options.jobsParallelism }}
      parallelism: {{ $job_options.jobsParallelism }}
      backoffLimit: 0
      template:
        metadata:
          labels:
            test: dbildings-iam-server-{{ $job_options.serviceName }}
            pod: {{ $job_name }}
        spec:
          automountServiceAccountToken: false
          containers:
          - name: {{ $job_name }}
            image: alpine:{{ $.Values.imageTag }}
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false            
            command: ["sh", "-c", 
                        "apk update && 
                        apk add --no-cache bash openssl curl cronie jq vim &&
                        chmod +x /scripts/*.sh &&
                        chmod 600 /etc/crontabs/root &&
                        touch /var/log/cron.log && 
                        chmod 644 /var/log/cron.log
                        ./scripts/trigger_xyz.sh "]
                        
            envFrom:
              - configMapRef:
                  name:  cronjob-envs-configmap
            
            volumeMounts:
            - name: secret-volume
              mountPath: /secrets
              readOnly: true
            - name: secret-volume-jwks
              mountPath: /keys
              readOnly: true
            - name: script-volume
              mountPath: /scripts

            ports:
            - containerPort: {{ $.Values.port }}
              name: dbildings-iam-server-trigger-xyz-pod  

          volumes:
          - name: script-volume
            configMap:
              name: cronjob-scripts-configmap
          - name: secret-volume-jwks
            secret:
              secretName: cronjob-secret-service-acc-jwks
          restartPolicy: Never
---
{{- end}}