{{- if .Values.cronjobs.enabled }}
{{- range $job_name, $job_options := .Values.cronjobs.jobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "common.names.namespace" $ }}-{{ $job_name}}
  namespace: {{ template "common.names.namespace" $ }}
spec:
  schedule: {{ $job_options.schedule }}
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            cron: {{ $job_name }}
        spec:
          automountServiceAccountToken: false
          containers:
          - name: {{ $job_name }}
            image: "{{ $.Values.cronjobs.image.repository }}:{{ $.Values.cronjobs.image.tag }}"
            imagePullPolicy: {{ .Values.cronjobs.image.pullPolicy | default "Always"}}
            securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
            envFrom:
              - configMapRef:
                  name:  cronjob-envs-configmap
            env:
                - name: BACKEND_ENDPOINT_URL
                  value: "https://{{ $.Values.backendHostname }}{{ $job_options.endpoint }}"
                - name: HTTP_METHOD
                  value: "{{ $job_options.httpMethod }}"
            resources:
              limits:
                memory: "128Mi"
                cpu: "200m"
              requests:
                memory: "64Mi"
                cpu: "50m"
            command:
              - "sh"
              - "-c"
              - |
                  apk update &&
                  mkdir /scripts &&
                  cp /scripts_tmp/*.sh /scripts/ &&
                  chmod +x /scripts/*.sh &&
                  chmod 600 /etc/crontabs/root &&
                  cd {{ $.Values.cronjobs.scriptDir }} &&
                  ./{{ $job_options.script }}
            volumeMounts:
              - name: secret-volume-jwks
                mountPath: /keys
                subPath: "service-account-private-jwks"
                readOnly: true
              - name: script-volume
                mountPath: /scripts_tmp
                readOnly: false
            ports:
            - containerPort: {{ $.Values.cronjobs.port }}
              name: cron-pod
          volumes:
          - name: script-volume
            configMap:
              name: cronjob-scripts-configmap
          - name: secret-volume-jwks
            secret:
              secretName: cronjob-secret-service-acc-jwks
              items:
              - key: service-account-private-jwks
                path: jwks.json
          restartPolicy: Never
---
{{- end}}
{{- end }}