---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cronjob-scripts-configmap
  namespace: {{ template "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  get-access-token-script: |-
    {{ .Files.Get "cron/scripts/get_access_token.sh" | nindent 4 }}
  trigger-xyz-script: |-
    {{ .Files.Get "cron/scripts/trigger_xyz.sh" | nindent 4 }}