apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cronjob-secret-service-acc-jwks
  namespace: {{ template "common.names.namespace" . }}
  labels: 
    app.kubernetes.io/managed-by: helm
spec:
  itemPath: "vaults/spsh-dev-schulportal/items/dbildungs-iam-server/sercive-account-private-jwks"