apiVersion: v1
kind: ConfigMap
metadata:
  name: { { template "common.names.name" . } }
  namespace: { { template "common.names.namespace" . } }
  labels: { { - include "common.labels" . | nindent 4 } }
data:
  config-json: |-
    {{ .Files.Get "config/email-config.json" | nindent 4 }}
  NODE_ENV: 'prod'
  DEPLOY_STAGE: { { .Values.environment | quote } }
