{{- if not .Values.emailMicroserviceAuth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.emailMicroserviceAuth.secretName }}
  namespace: {{ template "common.names.namespace" . }}
type: Opaque
data:
  db-host: {{ .Values.database.host }}
  db-password: {{ .Values.database.password }}
  db-username: {{ .Values.database.username }}
  ldap-bind-dn: {{ .Values.emailMicroserviceAuth.ldap_bind_dn }}
  ldap-admin-password: {{ .Values.emailMicroserviceAuth.ldap_admin_password }}
  secrets-json: {{ .Values.emailMicroserviceAuth.secrets_json }}
  ox-password: {{ .Values.emailMicroserviceAuth.ox_password }}
{{- end }}
