apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.names.releasename" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.dbildungsIamServer.commonLabels.name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://{{.Values.keycloakHostname}}"
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.backendHostname }}
      http:
        paths:
          - path: /api
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ (index .Values.backendports 0).port }}
          - path: /docs
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ (index .Values.backendports 0).port }}
          - path: /docs-json
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ (index .Values.backendports 0).port }}
          - path: /docs-json
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ (index .Values.backendports 0).port }}
          - path: /docs-yaml
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ (index .Values.backendports 0).port }}