---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.name" . }}-kafka-init-configmap
  namespace: {{ template "common.names.namespace" . }}
  labels: {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  create_topics.sh: |-
    {{ .Files.Get "kafka/scripts/create_topics.sh" | nindent 4 }}
  topics.txt: |-
    {{ .Files.Get "config/scripts/create_topics.sh" | nindent 4 }}
