apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.name" . }}-ldif
  namespace: {{ template "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  spsh-ldif: |-
    {{ .Files.Get "config/ldif/spsh.ldif" | nindent 4 }}

