{{- if not .Values.auth.existingSecret }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.name" . }}-ldap
  namespace: {{ template "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: server-ldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "common.names.name" . }}
      app.kubernetes.io/component: server-ldap
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: server-ldap
    spec:
      containers:
        - name: openldap
          image: "{{ .Values.ldap.image.repository }}:{{ .Values.ldap.image.tag }}"
          imagePullPolicy: {{ .Values.ldap.image.pullPolicy }}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "NET_RAW" ]
          args: [ "--copy-service", "--loglevel", "debug" ]
          resources: {{- toYaml .Values.ldap.resources | nindent 12 }}
          volumeMounts:
            - name: ldif-volume
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
            - name: ldap-certs
              mountPath: /container/service/slapd/assets/certs
          ports:
            - name: openldap
              containerPort: {{ .Values.ldap.service.ports.ldap }}
              protocol: TCP
          env:
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "common.names.name" . }}-ldap
                  key: admin-password
            - name: LDAP_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "common.names.name" . }}-ldap
                  key: config-password
          envFrom:
            - configMapRef:
                name: {{ template "common.names.name" . }}-ldap
      automountServiceAccountToken: false
      volumes:
        - name: ldif-volume
          configMap:
            name: {{ template "common.names.name" . }}-ldif
        - name: ldap-certs
          hostPath:
            path: "/data/ldap/certs"
      restartPolicy: {{ .Values.restartPolicy }}
{{- end }}
