apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}-ldap
  namespace: {{ template "common.names.namespace" . }}
type: Opaque
stringData:
  admin-password: {{ .Values.ldap.adminPassword }}
  config-password: {{ .Values.ldap.configPassword }}
