apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.name" . }}-redis
  namespace: {{ template "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: server-redis
spec:
  selector:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: server-redis
  type: {{ .Values.redis.service.type }}
  ports: 
    - name: redis
      port: {{ .Values.redis.service.ports.redis }}
      protocol: TCP

