apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "common.names.name" . }}-redis-tls-data"
  namespace: {{ template "common.names.namespace" . }}
  labels: 
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: server-redis
data:
{{(.Files.Glob "gencert.sh").AsConfig | indent 2}}
{{(.Files.Glob "copy-tls.sh").AsConfig | indent 2}}
{{(.Files.Glob "redis.conf").AsConfig | indent 2}}