apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.name" . }}-redis
  namespace: {{ template "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: server-redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "common.names.name" . }}
      app.kubernetes.io/component: server-redis
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: server-redis
    spec:
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      initContainers:
        - name: copy-tls-data
          image: alpine
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          command: ["/bin/sh","-c", "apk add --no-cache openssl bash;/bin/bash /tls/copy-tls.sh"]
          volumeMounts:
            - mountPath: "/tls"
              name: tls-data
            - mountPath: "/data"
              name: data
          resources: {{- toYaml .Values.redis.resources | nindent 12 }}
      containers:
        - name: {{ template "common.names.name" . }}-redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.containerPorts.redis }}
              protocol: TCP
          volumeMounts: 
            - mountPath: "/data"
              name: data
            {{- if .Values.redis.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.redis.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
          resources:resources: {{- toYaml .Values.redis.resources | nindent 12 }}
          livenessProbe: {{- toYaml .Values.redis.livenessProbe | nindent 12 }}
          readinessProbe: {{- toYaml .Values.redis.readinessProbe | nindent 12 }}
          startupProbe: {{- toYaml .Values.redis.startupProbe | nindent 12 }}
      volumes: 
        - name: tls-data
          configMap:
            name: dbildungs-iam-server-redis-tls-config
        - name: data
          emptyDir: {}
        {{- if .Values.redis.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.redis.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
