apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisservice.name }}
  namespace: {{ .Values.namespace }}
  labels: 
    app.kubernetes.io/name: {{ .Values.dbildungsIamServer.commonLabels.name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
spec:
  selector:
    app.kubernetes.io/layer: {{ .Values.redis.selector.layer }}
  type: {{ .Values.redisservicetype }}
  {{- if .Values.enabledredisserviceport }}
  ports: 
    {{- toYaml .Values.redisports | nindent 4 }}
  {{- end }}
