apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.name" . }}-redis
  namespace: {{ template "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: server-redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "common.names.name" . }}
      app.kubernetes.io/component: server-redis
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: server-redis
    spec:
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      initContainers:
        - name: copy-tls-data
          image: alpine
          securityContext: 
            allowPrivilegeEscalation: false
          command: ["/bin/sh","-c", "apk add --no-cache openssl bash;/bin/bash /tls/copy-tls.sh"]
          volumeMounts:
            - mountPath: "/tls"
              name: tls-data
            - mountPath: "/data"
              name: data
          resources: {{- toYaml .Values.redis.resources | nindent 12 }}
      containers:
        - name: {{ template "common.names.name" . }}-redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.containerPorts.redis }}
              protocol: TCP
          env: 
            {{- if .Values.redis.extraEnvVars }}
            {{ toYaml .Values.redis.extraEnvVars | nindent 12 }}
            {{- end }}
          volumeMounts: 
            - mountPath: "/data"
              name: data
            {{- with .Values.redis.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources: {{- toYaml .Values.redis.resources | nindent 12 }}
          livenessProbe: {{- omit .Values.redis.livenessProbe "enabled" | toYaml | nindent 12 }}
          readinessProbe: {{- omit .Values.redis.readinessProbe "enabled" | toYaml | nindent 12 }}
          startupProbe: {{- omit .Values.redis.startupProbe "enabled"| toYaml | nindent 12 }}
      volumes: 
        - name: tls-data
          configMap:
            name: {{ template "common.names.name" . }}-redis-tls-data
        - name: data
          emptyDir: {}
            {{- with .Values.redis.extraVolumes }}
            {{- toYaml . | nindent 8 }}
            {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
