apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels: 
    app.kubernetes.io/name: {{ .Values.dbildungs-iam-server.commonLabels.name }}
    app.kubernetes.io/version: {{.Chart.Version}}
spec:
  selector:
    app.kubernetes.io/layer: {{ .Values.backend.selector.layer }}
  type: {{ .Values.backendservicetype }}
  {{- if .Values.enabledbackendserviceport }}
  ports: {{- toYaml .Values.backendports | nindent 6 }}
  {{- end }}