0@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam linetype ortho
left to right direction
hide empty members
class Notification {
    name: string
}
class ExcludedPermission {
    name: string
}

together {
    class Permission
    class RolePermission
}
together {
    class AdditionalPersonProperty {
        value: any
    }
    class AdditionalPersonPropertyNames
}
class Person {
    externalId: string
    name
    ...
}
class UserRoleAssignment
class Role

class AuthenticationProvider
class DataProvider

class RolePermissionNodeAssignment

class SchoolStructureNode {
    externalId: string
    name: string
}
together {
    class Sponsor {
        type: enum
    }
    class Organization
    class Group
}
together {
    class ServiceProviderAccess
    class ServiceProviderLicence
    class ServiceProvider {
        accessProviderInSubnode: enum
    }
}
Notification ---> Person : target
Notification ---> Person : source

ExcludedPermission --> Person
ExcludedPermission --> RolePermission

RolePermission --> Permission
RolePermission --> ServiceProviderAccess

AdditionalPersonProperty --> AdditionalPersonPropertyNames
AdditionalPersonProperty --> Person

DataProvider -- Person

UserRoleAssignment --> Person
UserRoleAssignment --> Role
UserRoleAssignment --> SchoolStructureNode

Role --> SchoolStructureNode : administered by

AdditionalPersonPropertyNames --> Person

AuthenticationProvider -r-> DataProvider

SchoolStructureNode --> DataProvider
SchoolStructureNode -l-> SchoolStructureNode : administrative parent
SchoolStructureNode -r-> SchoolStructureNode : organizational parent

RolePermissionNodeAssignment --> SchoolStructureNode
RolePermissionNodeAssignment --> RolePermission
RolePermissionNodeAssignment --> Role

ServiceProviderAccess --> ServiceProvider

Organization -u-> SchoolStructureNode

Sponsor -u-> SchoolStructureNode

Group -u-> SchoolStructureNode

ServiceProviderLicence --> ServiceProvider
ServiceProviderLicence --> SchoolStructureNode

ServiceProvider --> SchoolStructureNode : administrated on

@enduml
