{{- if .Values.keycloakPublic}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
spec:
  tls:
    - hosts:
        - {{.Values.keycloakHostname}}
  ingressClassName: nginx
  rules:
    - host: keycloak.dev.spsh.dbildungsplattform.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 80
  {{end}}