name: Push Charts to helm-charts-registry on push to branch

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'charts/**'
      - '.github/workflows/**'

concurrency:
  group: dbildungs-iam-server-chart-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@1.3.1
    permissions:
      contents: read
  release:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@1.3.1
    secrets: inherit
    with:
      chart_name: dbildungs-iam
      version_generation: ticket_from_branch_short_hash
  
  branch_meta:
    uses: dBildungsplattform/spsh-app-deploy/.github/workflows/get-branch-meta.yml@main

  create_branch_identifier:
    needs: 
      - branch_meta
    uses: dBildungsplattform/spsh-app-deploy/.github/workflows/branch-to-namespace.yml@main
    with:
      branch: ${{ needs.branch_meta.outputs.branch }}

  deploy:
    needs:
      - branch_meta
      - create_branch_identifier
    uses: dBildungsplattform/spsh-app-deploy/.github/workflows/deploy.yml@main
    with:
      dbildungs_iam_server_branch: ${{ needs.branch_meta.outputs.ticket }}
      dbildungs_iam_client_branch: main
      dbildungs_iam_keycloak_branch: main
      namespace: ${{ needs.create_branch_identifier.outputs.namespace_from_branch }}
    secrets:
      SPSH_DEV_KUBECONFIG: ${{ secrets.SPSH_DEV_KUBECONFIG }}