name: Push Charts to helm-charts-registry manually with specified version

on:
  workflow_dispatch:
    inputs:
      chart_version:
        type: string
        description: "Chart version"
        required: true
      tag_generation:
        type: string
        description: "Tag generation"
        required: true

concurrency:
  group: dbildungs-iam-server-chart-manual
  cancel-in-progress: true

jobs:
  scan:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@1.3.1
    permissions:
      contents: read
  release:
    needs: scan
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@DBP-352-Set-the-correct-Docker-Image-in-the-Helm-chart-for-each-SPSH-repository
    secrets: inherit
    with:
      chart_name: dbildungs-iam
      version_generation: specified
      chart_version: ${{ inputs.chart_version }}
      tag_generation: ${{ inputs.tag_generation }}