name: Push Charts to helm-charts-registry on push to main (Merge)
on:
  push:
    branches:
      - 'main'

concurrency:
  group: dbildungs-iam-server-chart-main
  cancel-in-progress: true

jobs:
  release:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@DBP-352-Set-the-correct-Docker-Image-in-the-Helm-chart-for-each-SPSH-repository
    secrets: inherit
    with:
      chart_name: dbildungs-iam
      version_generation: short_hash
      tag_generation: commit_hash