name: Push Charts to helm-charts-registry

on:
  push:
    branches-ignore:
      - 'main'

concurrency:
  group: dbildungs-iam-server-chart-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@1.2.0
    permissions:
      contents: read
  get_ticket_sha:
    runs-on: ubuntu-latest
    outputs:
      ticket_number: ${{ steps.extract_ticket_number.outputs.output }}
      short_commit_hash: ${{ steps.trim_hash.outputs.output }}
    steps:
      - name: Extract ticket from branch
        id: extract_ticket_number
        run: |
          regex='^([[:alpha:]]+?-[[:digit:]]+)'
          [[ $GITHUB_REF_NAME =~ $regex ]]
          echo "output=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
      - name: Trim commit hash
        id: trim_hash
        run: |
          short_sha=`echo ${GITHUB_SHA} | cut -c1-8`
          echo "output=${short_sha}" >> $GITHUB_OUTPUT
  release:
    if: ${{ !failure() }}
    needs: [scan, get_ticket_sha]
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@DBP-282-workflow-release-helm-chart
    secrets: inherit
    with:
      chart_name: dbildungs-iam
      chart_version: "0.0.0-${{ needs.get_ticket_sha.outputs.ticket_number }}-${{ needs.get_ticket_sha.outputs.short_commit_hash }}"