name: Push Charts to helm-charts-registry on push to main (Merge)

on:
  push:
    branches:
      - 'main'
    paths:
      - 'charts/**'
      - '.github/workflows/**'

concurrency:
  group: dbildungs-iam-server-chart-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@DBP-282-workflow-release-helm-chart
    secrets: inherit
    with:
      chart_name: dbildungs-iam
      version_generation: short_hash