name: Push Charts to helm-charts-registry on push to branch

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'charts/**'
      - '.github/workflows/**'

concurrency:
  group: dbildungs-iam-server-chart-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@1.3.1
    permissions:
      contents: read
  release:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@1.3.1
    secrets: inherit
    with:
      chart_name: dbildungs-iam
      version_generation: ticket_from_branch_short_hash