name: "Clean and delete Kubernetes Namespace on branch deletion"

on:
  delete

concurrency:
  group: dbildungs-iam-server-${{ github.event_name }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  branch_meta:
    uses: dBildungsplattform/spsh-app-deploy/.github/workflows/get-branch-meta.yml@main

  create_branch_identifier:
    if: ${{ github.event_name == 'push' && !startsWith(github.ref_name,'dependabot/') }}
    needs: 
      - branch_meta
    uses: dBildungsplattform/spsh-app-deploy/.github/workflows/branch-to-namespace.yml@main
    with:
      branch: ${{ needs.branch_meta.outputs.branch }}

  delete_namespace:
    needs:
      - create_branch_identifier
    uses: dBildungsplattform/spsh-app-deploy/.github/workflows/delete-namespace.yml@main
    with:
      namespace: ${{ github.event.ref }}
    secrets:
      SPSH_DEV_KUBECONFIG: ${{ secrets.SPSH_DEV_KUBECONFIG }}

  deploy-successful:
    needs:
      - delete_namespace
      - create_branch_identifier
    runs-on: ubuntu-latest
    steps:
      - run: echo "Delete of namespace" ${{ needs.create_branch_identifier.outputs.namespace_from_branch }} "done" 