---
name: Deploy Project manually into dev cluster

on:
  workflow_dispatch:

jobs:
  branch_meta:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch_meta.outputs.branch }}
      sha: ${{ steps.extract_branch_meta.outputs.sha }}
    steps:
      - name: Extract branch meta
        shell: bash
        id: extract_branch_meta
        run: |
          if [ "${{ github.event_name }}" == 'pull_request' ]; then
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
            echo "sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
            echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs:
      - branch_meta
    uses: dBildungsplattform/spsh-app-deploy/.github/workflows/deploy.yml@main
    with:
      branch: ${{ needs.branch_meta.outputs.branch }}
    secrets:
      DEV_KUBE_CONFIG: ${{ secrets.SPSH_DEV_KUBECONFIG }}

  deploy-successful:
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy was successful"