name: 'Nest lint'
on:
  workflow_call:

jobs:
  nest_lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
      - name: Run linter
        run: npm run lint