name: 'Push to main Workflow'
env:
  NODE_VERSION: '18'
  DEPLOY_STAGE: 'dev'

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!main'

jobs:
  codeql_analyze:
    uses: ./.github/workflows/codeql_job.yml
  nest_lint:
    uses: ./.github/workflows/nest_lint_job.yml
  nest_test_and_sonarcloud:
    uses: ./.github/workflows/nest_test_sonarcloud_job.yml
    needs: [nest_lint]