name: 'On Pull Request or Push to main branch Workflow'
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  codeql_analyze:
    uses: ./.github/workflows/codeql_job.yml
  nest_lint:
    uses: ./.github/workflows/nest_lint_job.yml
  nest_test_and_sonarcloud:
    uses: ./.github/workflows/nest_test_sonarcloud_job.yml
    needs: [nest_lint]
    secrets: inherit