name: 'Push to main Workflow'

on:
  push:
    branches:
      - '*'
      - '!master'

env:
  NODE_VERSION: '18'
  DEPLOY_STAGE: 'dev'

jobs:
  codeql_analyze:
    uses: ./.github/workflows/codeql_job.yml
  nest_lint:
    uses: ./.github/workflows/nest_lint_job.yml
    with:
      NODE_VERSION: ${{ env.NODE_VERSION }}
  nest_test_and_sonarcloud:
    uses: ./.github/workflows/nest_test_sonarcloud_job.yml
    with:
      NODE_VERSION: ${{ env.NODE_VERSION }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}