name: 'Image to GHCR on push'

on:
  push:
    branches-ignore:
      - 'main'

permissions:
    contents: read

jobs:
#   codeql_analyze:
#     uses: ./.github/workflows/reusable_job_codeql.yml
#   nest_lint:
#     uses: ./.github/workflows/reusable_job_nest_lint.yml
#   nest_test_and_sonarcloud:
#     uses: ./.github/workflows/reusable_job_nest_test_sonarcloud.yml
#     secrets: inherit
#464a113d92f71479294351f078ee83aeb68b2694
  # branch_meta:
  #     runs-on: ubuntu-latest
  #     outputs:
  #       branch: ${{ steps.extract_branch_meta.outputs.branch }}
  #       sha: ${{ steps.extract_branch_meta.outputs.sha }}
  #     steps:
  #       - name: Extract branch meta
  #         shell: bash
  #         id: extract_branch_meta
  #         run: |
  #           echo "lowercase_repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
  #           echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
  #           echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT

  build_and_push:
    # if: ${{ !failure() }}
    # needs:
    #   - codeql_analyze
    #   - nest_lint
    #   - nest_test_and_sonarcloud
    #   - branch_meta
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-to-ghcr-trivy-on-push.yaml@464a113d92f71479294351f078ee83aeb68b2694
    with:
      image_name: dbildungsplattform/dbildungs-iam-server