name: 'Image to GHCR on push'

on:
  push:
    branches-ignore:
      - 'main'

permissions:
    contents: read

jobs:
#   codeql_analyze:
#     uses: ./.github/workflows/reusable_job_codeql.yml
#   nest_lint:
#     uses: ./.github/workflows/reusable_job_nest_lint.yml
#   nest_test_and_sonarcloud:
#     uses: ./.github/workflows/reusable_job_nest_test_sonarcloud.yml
#     secrets: inherit

  build_and_push:
    # if: ${{ !failure() }}
    # needs:
    #   - codeql_analyze
    #   - nest_lint
    #   - nest_test_and_sonarcloud
    permissions:
      actions: read
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-to-ghcr-trivy-on-push.yaml@464a113d92f71479294351f078ee83aeb68b2694
    with:
      image_name: dbildungs-iam-server