name: 'Image to GHCR on push'

on:
  push:
    branches-ignore:
      - 'main'

permissions:
    contents: read

jobs:
  codeql_analyze:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-codeql.yaml@3e2c4d2d0277d5621dcb60d85273a358dac9ac90
    permissions:
      actions: read
      contents: read
      security-events: write
  nest_lint:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-nest-lint.yaml@3e2c4d2d0277d5621dcb60d85273a358dac9ac90
    with:
      node_version: '18'
    permissions:
      contents: read
  nest_test_and_sonarcloud:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-nest-test-sonarcloud.yaml@3e2c4d2d0277d5621dcb60d85273a358dac9ac90
    with:
      node_version: '18'
      deploy_stage: 'dev'
    permissions:
      contents: read
    secrets: inherit

  build_and_push:
    if: ${{ !failure() }}
    needs:
      - codeql_analyze
      - nest_lint
      - nest_test_and_sonarcloud
    permissions:
      actions: read
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-to-ghcr-trivy-on-push.yaml@464a113d92f71479294351f078ee83aeb68b2694
    with:
      image_name: dbildungs-iam-server