name: 'Image to GHCR on push to branch'

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  codeql_analyze:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-codeql.yaml@1.1.0
    permissions:
      actions: read
      contents: read
      security-events: write
  nest_lint:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-nest-lint.yaml@1.1.0
    with:
      node_version: '18'
    permissions:
      contents: read
  nest_test_and_sonarcloud:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-nest-test-sonarcloud.yaml@1.1.0
    with:
      node_version: '18'
      deploy_stage: 'dev'
    permissions:
      contents: read
    secrets: inherit

  build_and_push:
    if: ${{ !failure() }}
    needs:
      - codeql_analyze
      - nest_lint
      - nest_test_and_sonarcloud
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@1.0.0
    with:
      image_name: "dbildungs-iam-server"
      container_registry: "ghcr.io"
      tag_generation: "ticket_from_branch"
      run_trivy_scan: true