name: 'Image to GHCR on push'

on:
  workflow_run:
    workflows: ['All static tests on every push']
    types: [completed]
    branches-ignore:
        - 'main'

permissions:
    contents: read

jobs:
    branch_meta:
        runs-on: ubuntu-latest
        outputs:
          branch: ${{ steps.extract_branch_meta.outputs.branch }}
          sha: ${{ steps.extract_branch_meta.outputs.sha }}
        steps:
          - name: Extract branch meta
            shell: bash
            id: extract_branch_meta
            run: |
              echo "lowercase_repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
              if [ "${{ github.event_name }}" == 'pull_request' ]; then
                echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
                echo "sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
              else
                echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
                echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
              fi
