name: Push Charts to helm-charts-registry

on:
  push:
    tags:
      - 'dbildungs-iam-*'

jobs:
  scan:
    uses: ./.github/workflows/reusable_job_kics.yml

  release:
    if: ${{ !failure() }}
    needs: [scan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com" 

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.5.0 

      - name: Helm Repository Checkout
        uses: actions/checkout@v3
        with:
          repository: dBildungsplattform/helm-charts-registry
          token: ${{ secrets.HELM_CHARTS_REGISTRY_PUBLISHER }}
          fetch-depth: 0
          persist-credentials: true
          ref: main
          path: helm-charts-registry
      - name: Prepare Helm Chart
        run:  |
          # dbildungs-iam
          helm package charts/dbildungs-iam -d helm-charts-registry
          cd helm-charts-registry
          if [ -d "automation/dbildungs-iam" ]; then rm -r automation/dbildungs-iam; fi
          tar -xzf dbildungs-iam*.tgz
          mv dbildungs-iam automation/dbildungs-iam
      - name: Push Helm Chart
        env:
          GITHUB_TOKEN: ${{ secrets.HELM_CHARTS_REGISTRY_PUBLISHER }}
        run: |
          git config --global user.email "dbildungs-iam@dbildungsplattform.de"
          git config --global user.name "dbildungs-iam-gha"
          CHART_PACKAGE_NAMES="dbildungs-iam"
          cd helm-charts-registry/automation
          git add $CHART_PACKAGE_NAMES
          git commit -m "$CHART_PACKAGE_NAMES"
          git push origin main