name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]

env:
    NODE_VERSION: '18'

jobs:
    nest_test_cov:
        name: Test
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v3
          - name: docker check
            run: docker --version
          - name: Setup node
            uses: actions/setup-node@v3
            with:
              node-version: ${{ env.NODE_VERSION }}
          - name: npm ci
            run: npm ci --prefer-offline --no-audit
          - name: jest
            run: npm run test:ci
          - name: save coverage artifacts
            run: |
              mkdir -p artifacts
              mv ./coverage/lcov.info artifacts/
          - name: upload artifacts
            uses: actions/upload-artifact@v3
            with:
              name: coverage-artifacts
              path: artifacts/
    nest_lint:
     name: Lint
     runs-on: ubuntu-latest
     timeout-minutes: 5
     steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm ci
        run: npm ci --prefer-offline --no-audit
      - name: eslint
        run: npm run lint
    sonarcloud:
        name: sonarcloud coverage
        runs-on: ubuntu-latest
        needs: [nest_test_cov]
        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: download coverage artifacts
          uses: actions/download-artifact@v3
          with:
            name: coverage-artifacts
            path: coverage/
        - name: SonarCloud upload coverage
          uses: SonarSource/sonarcloud-github-action@v1.9
          env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
          with:
            args: -X
